clients.ts.build:
  stage: build
  dependencies: []
  rules:
    - changes:
        - clients/ts/**/*
  image: node:$NODE_VERSION
  script:
    - pushd clients/ts/
    - npm ci
    - npm run build
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - clients/ts/node_modules/
      - clients/ts/dist/

clients.ts.check:
  stage: test
  dependencies:
    - clients.ts.build
  rules:
    - changes:
        - clients/ts/**/*
  image: node:$NODE_VERSION
  script:
    - pushd clients/ts/
    - npm run check
