client.rust.check:
  stage: test
  dependencies: []
  image: rust:$RUST_VERSION
  rules:
    - changes:
        - clients/rust/**/*
        - Cargo.*
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - pushd clients/rust
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test --all-targets --all-features
    - cargo clippy --all-targets --no-default-features --features reqwest-rustls-tls-webpki-roots,consumer -- -D warnings
    - cargo test --all-targets --no-default-features --features reqwest-rustls-tls-webpki-roots,consumer
    - cargo clippy --all-targets --no-default-features --features reqwest-rustls-tls-webpki-roots,producer -- -D warnings
    - cargo test --all-targets --no-default-features --features reqwest-rustls-tls-webpki-roots,producer

client.rust.semver-checks:
  stage: test
  dependencies: []
  image: rust:$RUST_VERSION
  variables:
    BINSTALL_DISABLE_TELEMETRY: "true"
  rules:
    - changes:
        - clients/rust/**/*
        - Cargo.*
  before_script:
    - rustc --version && cargo --version
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall cargo-semver-checks -y
  script:
    - pushd clients/rust
    - cargo semver-checks
