[package]
name = "hook0-client"
version = "0.1.1"
edition = "2021"
description = "Rust SDK for Hook0 Open-Source Webhooks as a service for SaaS"
authors = ["David Sferruzza <david@hook0.com>", "François-Guillaume Ribreau <fg@hook0.com>"]
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook-server", "events", "saas"]
homepage = "https://www.hook0.com/"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
hex = "0.4.3"
hmac = "0.12.1"
lazy-regex = "3.4.1"
log = "0.4.25"
reqwest = { version = "0.12.12", default-features = false, features = ["hickory-dns", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
sha2 = "0.10.8"
thiserror = "2.0.11"
url = "2.5.4"
uuid = { version = "1.12.1", features = ["serde", "v4"] }

[dev-dependencies]
actix-web = { version = "4.9.0", default-features = false, features = ["macros"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots", "producer"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
consumer = []
producer = []

[[example]]
name = "actix-web"
path = "examples/actix-web.rs"
required-features = ["consumer"]
